package model.achievement;

import java.util.List;

import static model.achievement.AchievementTier.*;

// Represents lists of all possible achievements
public class AchievementList {
    protected static final List<Achievement> DAILY_ACHIEVEMENTS = List.of(
            new Achievement("Streak Starter",
                    "Reach the habit target for 1 day", 1, AchievementType.STREAK, BRONZE),
            new Achievement("Double Trouble",
                    "Reach the habit target for 2 days in a row", 2, AchievementType.STREAK, BRONZE),
            new Achievement("Oh Baby A Triple",
                    "Reach the habit target for 3 days in a row", 3, AchievementType.STREAK, BRONZE),
            new Achievement("Streak Apprentice",
                    "Reach the habit target for 4 days in a row", 4, AchievementType.STREAK, BRONZE),
            new Achievement("Streak Challenger",
                    "Reach the habit target for 5 days in a row", 5, AchievementType.STREAK, BRONZE),
            new Achievement("Streak Master",
                    "Reach the habit target for 10 days in a row", 10, AchievementType.STREAK, BRONZE),
            new Achievement("Streak Veteran",
                    "Reach the habit target for 15 days in a row", 15, AchievementType.STREAK, BRONZE),
            new Achievement("Streak Warrior",
                    "Reach the habit target for 20 days in a row", 20, AchievementType.STREAK, BRONZE),
            new Achievement("Monthly Maestro",
                    "Reach the habit target for 30 days in a row", 30, AchievementType.STREAK, BRONZE),
            new Achievement("Streak Virtuoso",
                    "Reach the habit target for 35 days in a row", 35, AchievementType.STREAK, SILVER),
            new Achievement("Streak Hero",
                    "Reach the habit target for 40 days in a row", 40, AchievementType.STREAK, SILVER),
            new Achievement("Streak Elite",
                    "Reach the habit target for 45 days in a row", 45, AchievementType.STREAK, SILVER),
            new Achievement("Streak Grandmaster",
                    "Reach the habit target for 50 days in a row", 50, AchievementType.STREAK, SILVER),
            new Achievement("Streak Legend",
                    "Reach the habit target for 60 days in a row", 60, AchievementType.STREAK, SILVER),
            new Achievement("Streak Champion",
                    "Reach the habit target for 70 days in a row", 70, AchievementType.STREAK, SILVER),
            new Achievement("Streak Superstar",
                    "Reach the habit target for 80 days in a row", 80, AchievementType.STREAK, SILVER),
            new Achievement("Streak Emperor",
                    "Reach the habit target for 90 days in a row", 90, AchievementType.STREAK, SILVER),
            new Achievement("Streak God",
                    "Reach the habit target for 100 days in a row", 100, AchievementType.STREAK, GOLD),
            new Achievement("Streak Wizard",
                    "Reach the habit target for 120 days in a row", 120, AchievementType.STREAK, GOLD),
            new Achievement("Streak Overlord",
                    "Reach the habit target for 140 days in a row", 140, AchievementType.STREAK, GOLD),
            new Achievement("Streak Titan",
                    "Reach the habit target for 160 days in a row", 160, AchievementType.STREAK, GOLD),
            new Achievement("Streak Sovereign",
                    "Reach the habit target for 180 days in a row", 180, AchievementType.STREAK, GOLD),
            new Achievement("Streak Star",
                    "Reach the habit target for 200 days in a row", 200, AchievementType.STREAK, GOLD),
            new Achievement("Streak Deity",
                    "Reach the habit target for 250 days in a row", 250, AchievementType.STREAK, GOLD),
            new Achievement("Streak Yoda",
                    "Reach the habit target for 300 days in a row", 300, AchievementType.STREAK, GOLD),
            new Achievement("Yearly Ace",
                    "Reach the habit target for 365 days in a row", 365, AchievementType.STREAK, PLATINUM),
            new Achievement("First Time?",
                    "Complete the habit for the first time", 1, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Second Time's the Charm",
                    "Complete the habit for the second time", 2, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Triple Triumph",
                    "Complete the habit for the third time", 3, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Quadruple Quest",
                    "Complete the habit for the fourth time", 4, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Quintuple Quest",
                    "Complete the habit for the fifth time", 5, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Deca-Daily",
                    "Complete the habit 10 times", 10, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Fifteen Feats",
                    "Complete the habit 15 times", 15, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Twenty Triumphs",
                    "Complete the habit 20 times", 20, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Three Zero",
                    "Complete the habit 30 times", 30, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Quadruple Zero",
                    "Complete the habit 40 times", 40, AchievementType.SINGULAR_SUCCESSES, SILVER),
            new Achievement("Fifty Feats",
                    "Complete the habit 50 times", 50, AchievementType.SINGULAR_SUCCESSES, SILVER),
            new Achievement("Century Club",
                    "Complete the habit 100 times", 100, AchievementType.SINGULAR_SUCCESSES, SILVER),
            new Achievement("Double Century",
                    "Complete the habit 200 times", 200, AchievementType.SINGULAR_SUCCESSES, SILVER),
            new Achievement("Triple Century",
                    "Complete the habit 300 times", 300, AchievementType.SINGULAR_SUCCESSES, SILVER),
            new Achievement("Quadruple Century",
                    "Complete the habit 400 times", 400, AchievementType.SINGULAR_SUCCESSES, GOLD),
            new Achievement("Quintuple Century",
                    "Complete the habit 500 times", 500, AchievementType.SINGULAR_SUCCESSES, GOLD),
            new Achievement("Six Centuries?!?",
                    "Complete the habit 600 times", 600, AchievementType.SINGULAR_SUCCESSES, GOLD),
            new Achievement("Eighth Wonder",
                    "Complete the habit 800 times", 800, AchievementType.SINGULAR_SUCCESSES, GOLD),
            new Achievement("Millennium Master",
                    "Complete the habit 1000 times", 1000, AchievementType.SINGULAR_SUCCESSES, GOLD),
            new Achievement("Double Millennium",
                    "Complete the habit 2000 times", 2000, AchievementType.SINGULAR_SUCCESSES, PLATINUM),
            new Achievement("A New Beginning",
                    "Reach the habit target for the first time", 1, AchievementType.PERIODIC_SUCCESSES, BRONZE),
            new Achievement("Double Down",
                    "Reach the habit target for 2 days", 2, AchievementType.PERIODIC_SUCCESSES, BRONZE),
            new Achievement("Triple Threat",
                    "Reach the habit target for 3 days", 3, AchievementType.PERIODIC_SUCCESSES, BRONZE),
            new Achievement("Habit Quarter",
                    "Reach the habit target for 4 days", 4, AchievementType.PERIODIC_SUCCESSES, BRONZE),
            new Achievement("The Quintessential Habit",
                    "Reach the habit target for 5 days", 5, AchievementType.PERIODIC_SUCCESSES, BRONZE),
            new Achievement("Deca-days",
                    "Reach the habit target for 10 days", 10, AchievementType.PERIODIC_SUCCESSES, BRONZE),
            new Achievement("Twenty Twenty",
                    "Reach the habit target for 20 days", 20, AchievementType.PERIODIC_SUCCESSES, BRONZE),
            new Achievement("Thirty Thirty",
                    "Reach the habit target for 30 days", 30, AchievementType.PERIODIC_SUCCESSES, BRONZE),
            new Achievement("Forty Forty",
                    "Reach the habit target for 40 days", 40, AchievementType.PERIODIC_SUCCESSES, SILVER),
            new Achievement("Fifty Fifty",
                    "Reach the habit target for 50 days", 50, AchievementType.PERIODIC_SUCCESSES, SILVER),
            new Achievement("Century Habit",
                    "Reach the habit target for 100 days", 100, AchievementType.PERIODIC_SUCCESSES, SILVER),
            new Achievement("Double Century Habit",
                    "Reach the habit target for 200 days", 200, AchievementType.PERIODIC_SUCCESSES, GOLD),
            new Achievement("A Year of Habits",
                    "Reach the habit target for 365 days", 365, AchievementType.PERIODIC_SUCCESSES, GOLD),
            new Achievement("Habit Half a Millennium",
                    "Reach the habit target for 500 days", 500, AchievementType.PERIODIC_SUCCESSES, GOLD),
            new Achievement("Habit Millennium",
                    "Reach the habit target for 1000 days", 1000, AchievementType.PERIODIC_SUCCESSES, PLATINUM),
            new Achievement("Habit Born",
                    "Track the habit for 1 day", 1, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("Habit Toddler",
                    "Track the habit for 2 days", 2, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("Habit Child",
                    "Track the habit for 3 days", 3, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("Habit Teen",
                    "Track the habit for 4 days", 4, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("Habit Adult",
                    "Track the habit for 5 days", 5, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("Exists 10?",
                    "Track the habit for 10 days", 10, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("20's",
                    "Track the habit for 20 days", 20, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("30's",
                    "Track the habit for 30 days", 30, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("40's",
                    "Track the habit for 40 days", 40, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("50's",
                    "Track the habit for 50 days", 50, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("Tracker Perfect",
                    "Track the habit for 100 days", 100, AchievementType.PERIOD_COUNT, SILVER),
            new Achievement("Tracker Heaven",
                    "Track the habit for 250 days", 250, AchievementType.PERIOD_COUNT, SILVER),
            new Achievement("Year-Old Habit",
                    "Track the habit for 365 days", 365, AchievementType.PERIOD_COUNT, SILVER),
            new Achievement("Tracker God",
                    "Track the habit for 500 days", 500, AchievementType.PERIOD_COUNT, GOLD),
            new Achievement("Millennial Habit",
                    "Track the habit for 1000 days", 1000, AchievementType.PERIOD_COUNT, GOLD),
            new Achievement("Tracker 2000",
                    "Track the habit for 2000 days", 2000, AchievementType.PERIOD_COUNT, PLATINUM)
    );
    protected static final List<Achievement> WEEKLY_ACHIEVEMENTS = List.of(
            new Achievement("Weekly Streak Initiator",
                    "Reach the habit target for 1 week", 1, AchievementType.STREAK, BRONZE),
            new Achievement("Weekly Streaker",
                    "Reach the habit target for 2 weeks in a row", 2, AchievementType.STREAK, BRONZE),
            new Achievement("Streak Thrice",
                    "Reach the habit target for 3 weeks in a row", 3, AchievementType.STREAK, BRONZE),
            new Achievement("A Month of Streaks",
                    "Reach the habit target for 4 weeks in a row", 4, AchievementType.STREAK, SILVER),
            new Achievement("Five for Five",
                    "Reach the habit target for 5 weeks in a row", 5, AchievementType.STREAK, SILVER),
            new Achievement("Streak Deca",
                    "Reach the habit target for 10 weeks in a row", 10, AchievementType.STREAK, GOLD),
            new Achievement("Streak Champion",
                    "Reach the habit target for 20 weeks in a row", 20, AchievementType.STREAK, GOLD),
            new Achievement("Yearly Streaker",
                    "Reach the habit target for 52 weeks in a row", 52, AchievementType.STREAK, PLATINUM),
            new Achievement("Weekly First Time?",
                    "Complete the habit for the first time", 1, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Double Completion",
                    "Complete the habit for the second time", 2, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Triple Completion",
                    "Complete the habit for the third time", 3, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Quadruple Completion",
                    "Complete the habit for the fourth time", 4, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Quintuple Completion",
                    "Complete the habit for the fifth time", 5, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Deca-Weekly",
                    "Complete the habit 10 times", 10, AchievementType.SINGULAR_SUCCESSES, SILVER),
            new Achievement("Fifteen Feats",
                    "Complete the habit 15 times", 15, AchievementType.SINGULAR_SUCCESSES, SILVER),
            new Achievement("Twenty Triumphs",
                    "Complete the habit 20 times", 20, AchievementType.SINGULAR_SUCCESSES, SILVER),
            new Achievement("Three Zero",
                    "Complete the habit 30 times", 30, AchievementType.SINGULAR_SUCCESSES, GOLD),
            new Achievement("Quadruple Zero",
                    "Complete the habit 40 times", 40, AchievementType.SINGULAR_SUCCESSES, GOLD),
            new Achievement("Fifty Feats",
                    "Complete the habit 50 times", 50, AchievementType.SINGULAR_SUCCESSES, GOLD),
            new Achievement("Century Club",
                    "Complete the habit 100 times", 100, AchievementType.SINGULAR_SUCCESSES, GOLD),
            new Achievement("Completionist",
                    "Complete the habit 250 times", 250, AchievementType.SINGULAR_SUCCESSES, PLATINUM),
            new Achievement("A New Weekly Beginning",
                    "Reach the habit target for the first time", 1, AchievementType.PERIODIC_SUCCESSES, BRONZE),
            new Achievement("Double Down",
                    "Reach the habit target for 2 weeks", 2, AchievementType.PERIODIC_SUCCESSES, BRONZE),
            new Achievement("Triple Threat",
                    "Reach the habit target for 3 weeks", 3, AchievementType.PERIODIC_SUCCESSES, BRONZE),
            new Achievement("Habit Quarter",
                    "Reach the habit target for 4 weeks", 4, AchievementType.PERIODIC_SUCCESSES, BRONZE),
            new Achievement("The Quintessential Habit",
                    "Reach the habit target for 5 weeks", 5, AchievementType.PERIODIC_SUCCESSES, BRONZE),
            new Achievement("Deca-Weeks",
                    "Reach the habit target for 10 weeks", 10, AchievementType.PERIODIC_SUCCESSES, SILVER),
            new Achievement("Twenty Twenty",
                    "Reach the habit target for 20 weeks", 20, AchievementType.PERIODIC_SUCCESSES, SILVER),
            new Achievement("Thirty Thirty",
                    "Reach the habit target for 30 weeks", 30, AchievementType.PERIODIC_SUCCESSES, SILVER),
            new Achievement("Forty Forty",
                    "Reach the habit target for 40 weeks", 40, AchievementType.PERIODIC_SUCCESSES, GOLD),
            new Achievement("Habit Year",
                    "Reach the habit target for 52 weeks", 52, AchievementType.PERIODIC_SUCCESSES, GOLD),
            new Achievement("Century Habit",
                    "Reach the habit target for 100 weeks", 100, AchievementType.PERIODIC_SUCCESSES, PLATINUM),
            new Achievement("Habit Born",
                    "Track the habit for 1 week", 1, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("Habit Toddler",
                    "Track the habit for 2 weeks", 2, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("Habit Child",
                    "Track the habit for 3 weeks", 3, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("Habit Teen",
                    "Track the habit for 4 weeks", 4, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("Habit Adult",
                    "Track the habit for 5 weeks", 5, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("Exists 10?",
                    "Track the habit for 10 weeks", 10, AchievementType.PERIOD_COUNT, SILVER),
            new Achievement("20's",
                    "Track the habit for 20 weeks", 20, AchievementType.PERIOD_COUNT, SILVER),
            new Achievement("30's",
                    "Track the habit for 30 weeks", 30, AchievementType.PERIOD_COUNT, SILVER),
            new Achievement("40's",
                    "Track the habit for 40 weeks", 40, AchievementType.PERIOD_COUNT, SILVER),
            new Achievement("Year of Tracking",
                    "Track the habit for 52 weeks", 52, AchievementType.PERIOD_COUNT, GOLD),
            new Achievement("Tracker Perfect",
                    "Track the habit for 100 weeks", 100, AchievementType.PERIOD_COUNT, GOLD),
            new Achievement("Double Century Tracker",
                    "Track the habit for 200 weeks", 200, AchievementType.PERIOD_COUNT, PLATINUM)
    );

    protected static final List<Achievement> MONTHLY_ACHIEVEMENTS = List.of(
            new Achievement("Monthly Streak Initiator",
                    "Reach the habit target for 1 month", 1, AchievementType.STREAK, BRONZE),
            new Achievement("Monthly Streaker",
                    "Reach the habit target for 2 months in a row", 2, AchievementType.STREAK, BRONZE),
            new Achievement("Streak Thrice",
                    "Reach the habit target for 3 months in a row", 3, AchievementType.STREAK, BRONZE),
            new Achievement("A Quarter of Streaks",
                    "Reach the habit target for 4 months in a row", 4, AchievementType.STREAK, SILVER),
            new Achievement("Five for Five",
                    "Reach the habit target for 5 months in a row", 5, AchievementType.STREAK, SILVER),
            new Achievement("Yearly Streaker",
                    "Reach the habit target for 12 months in a row", 12, AchievementType.STREAK, GOLD),
            new Achievement("Streak Champion",
                    "Reach the habit target for 20 months in a row", 20, AchievementType.STREAK, PLATINUM),
            new Achievement("Monthly First Time?",
                    "Complete the habit for the first time", 1, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Double Completion",
                    "Complete the habit for the second time", 2, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Triple Completion",
                    "Complete the habit for the third time", 3, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Quadruple Completion",
                    "Complete the habit for the fourth time", 4, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Quintuple Completion",
                    "Complete the habit for the fifth time", 5, AchievementType.SINGULAR_SUCCESSES, BRONZE),
            new Achievement("Deca-Monthly",
                    "Complete the habit 10 times", 10, AchievementType.SINGULAR_SUCCESSES, SILVER),
            new Achievement("Fifteen Feats",
                    "Complete the habit 15 times", 15, AchievementType.SINGULAR_SUCCESSES, SILVER),
            new Achievement("Twenty Triumphs",
                    "Complete the habit 20 times", 20, AchievementType.SINGULAR_SUCCESSES, SILVER),
            new Achievement("Three Zero",
                    "Complete the habit 30 times", 30, AchievementType.SINGULAR_SUCCESSES, GOLD),
            new Achievement("Quadruple Zero",
                    "Complete the habit 40 times", 40, AchievementType.SINGULAR_SUCCESSES, GOLD),
            new Achievement("Fifty Feats",
                    "Complete the habit 50 times", 50, AchievementType.SINGULAR_SUCCESSES, GOLD),
            new Achievement("Century Club",
                    "Complete the habit 100 times", 100, AchievementType.SINGULAR_SUCCESSES, GOLD),
            new Achievement("Completionist",
                    "Complete the habit 200 times", 200, AchievementType.SINGULAR_SUCCESSES, PLATINUM),
            new Achievement("A New Monthly Beginning",
                    "Reach the habit target for the first time", 1, AchievementType.PERIODIC_SUCCESSES, BRONZE),
            new Achievement("Double Down",
                    "Reach the habit target for 2 months", 2, AchievementType.PERIODIC_SUCCESSES, BRONZE),
            new Achievement("Triple Threat",
                    "Reach the habit target for 3 months", 3, AchievementType.PERIODIC_SUCCESSES, SILVER),
            new Achievement("Habit Quarter",
                    "Reach the habit target for 4 months", 4, AchievementType.PERIODIC_SUCCESSES, SILVER),
            new Achievement("The Quintessential Habit",
                    "Reach the habit target for 5 months", 5, AchievementType.PERIODIC_SUCCESSES, GOLD),
            new Achievement("Yearly Habit",
                    "Reach the habit target for 12 months", 12, AchievementType.PERIODIC_SUCCESSES, PLATINUM),
            new Achievement("Habit Born",
                    "Track the habit for 1 month", 1, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("Habit Toddler",
                    "Track the habit for 2 months", 2, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("Triple Track",
                    "Track the habit for 3 months", 3, AchievementType.PERIOD_COUNT, BRONZE),
            new Achievement("Tracker Quarter",
                    "Track the habit for 4 months", 4, AchievementType.PERIOD_COUNT, SILVER),
            new Achievement("The Quintessential Tracker",
                    "Track the habit for 5 months", 5, AchievementType.PERIOD_COUNT, SILVER),
            new Achievement("A Year of Tracking",
                    "Track the habit for 12 months", 12, AchievementType.PERIOD_COUNT, GOLD),
            new Achievement("Double Year Tracker",
                    "Track the habit for 24 months", 24, AchievementType.PERIOD_COUNT, GOLD),
            new Achievement("Triple Year Tracker",
                    "Track the habit for 36 months", 36, AchievementType.PERIOD_COUNT, PLATINUM)
    );
}